#!/bin/sh
#
# @name XE4T
#
# @type VTOL Tiltrotor
# @class VTOL
#
# @maintainer G Kashyap 
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 motor 5
# @output MAIN6 motor 6
# @output MAIN7 motor 7
# @output MAIN8 motor 8
# @output AUX1 Aileron 1
# @output AUX2 Aileron 2
# @output AUX3 Elevator
# @output AUX4 Rudder
# @output AUX5 Throttle
# @output AUX6 Tilt servo
#
# @board px4_fmu-v2 exclude
# @board intel_aerofc-v1 exclude
# @board bitcraze_crazyflie exclude
#

sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
	param set PWM_AUX_DISARMED 1000
	param set PWM_AUX_MAX 2000
	param set PWM_AUX_MIN 1000
	param set PWM_AUX_RATE 50

	param set PWM_MAX 2000
	param set PWM_RATE 400

	param set VT_MOT_ID 12345678

	param set VT_FW_MOT_OFFID 2468	

	
  param set VT_IDLE_PWM_MC 1080
	param set VT_TILT_FW 0.9
	param set VT_TILT_MC 0.08
	param set VT_TILT_TRANS 0.5
	param set VT_ELEV_MC_LOCK 0
	param set VT_TYPE 1
fi

set MAV_TYPE 21

set MIXER xe4t
set MIXER_AUX xe4t


set PWM_OUT 12345678
